### ISSUE TITLE
Typo in the entry "cpp-httplib"

### ISSUE THREAD

**Issue by liurui39660** [fffaraz/awesome-cpp#1054]
In the section Networking, there's an entry:

> cpp-httplib - A single file C++11 header-only HTTP/HTTPS sever library. [MIT]

It seems the "sever" should be "server".

**Comment by myd7349** [comment]
Hi! @liurui39660 Thanks for your suggestion. Feel free to create a PR. :-)

**Comment by myd7349** [comment]
Fixed by #1090 . Thanks.
