### ISSUE TITLE
some libraries are old and i think need to be remove

### ISSUE THREAD

**Issue by hamedmohammadi** [fffaraz/awesome-cpp#115]
Reason library does not developed since 2008 in my first search but some library  like Dijini from dropbox to use c++ in android and ios exists
should i send you a pull request

**Comment by fffaraz** [comment]
100% Agree.
Maybe we should add a new category for them like "Deprecated Libs".
I guess most of them still hosted on Google code are already abandoned.

**Comment by hamedmohammadi** [comment]
okey let me do it this weekend .
don't you think showing deprecated in libs will confuse user and is not
beneficial.
it is good to show old one for get experience of  their problems but in a
seprate page or at the buttom of page
