### ISSUE TITLE
Add build status of each repo

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [fffaraz/awesome-cpp#1197]
Thanks for maintaining such an awesome repo!

Maybe we can add build status of each repo like [awesome-rust](https://github.com/rust-unofficial/awesome-rust)

* [ni-media](https://github.com/NativeInstruments/ni-media) - C++ library for reading and writing audio files. [MIT] [![Build Status](https://dev.azure.com/mohinda/ni-media/_apis/build/status/marcrambo.ni-media?branchName=master)](https://dev.azure.com/mohinda/ni-media/_build/latest?definitionId=1&branchName=master)

**Comment by MartinDelille** [comment]
I agree but adding each repository would be a huge task. You could start making a PR for [ni-media](https://github.com/NativeInstruments/ni-media) ?

**Comment by Lloyd-Pottiger** [comment]
> I agree but adding each repository would be a huge task. You could start making a PR for [ni-media](https://github.com/NativeInstruments/ni-media) ?

done, please have a review
