### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by arthurvr** [fffaraz/awesome-cpp#128]
This repo seems to miss a license :wink:

Ref https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by fffaraz** [comment]
I'm not sure but maybe because I don't care about a bunch of text that nobody actually reads it.

**Comment by arthurvr** [comment]
Try to keep in mind that not having a license means that people are not allowed to reproduce, distribute or create derivative works. I know most people probably don't care, but in professional circumstances it can really make sense (and can really limit people)

**Comment by Calinou** [comment]
[sindresorhus/awesome](https://github.com/sindresorhus/awesome) recommends using CC0 1.0 Universal as a license, which is quite short and suitable for everything.

**Comment by Calinou** [comment]
Please use a formal license instead. You seem to have based this on the [WTFPL](https://gnu.org/licenses/license-list#WTFPL), a license with strong language and that lacks a warranty disclaimer.
