### ISSUE TITLE
cpprestsdk is in maintenance mode and we do not recommend its use in new projects

### ISSUE THREAD

**Issue by brccabral** [fffaraz/awesome-cpp#1418]
Hi,
Should awesome-cpp still recommend C++ REST SDK?

https://github.com/Microsoft/cpprestsdk
```
cpprestsdk is in maintenance mode and we do not recommend its use in new projects
```

Thanks,
Bruno

**Comment by fffaraz** [comment]
It's good enough to be listed. It's not a recommendation list.
