### ISSUE TITLE
Add some C++ code so repo would be recognized by github as C++

### ISSUE THREAD

**Issue by MyLittleRobo** [fffaraz/awesome-cpp#231]
Just hello world main.cpp should be enough I guess.

That will help to find this repo in the starred list when filtering it by programming language.

**Comment by vikaskyadav** [comment]
where do we have to write the code? Help needed.

**Comment by nabijaczleweli** [comment]
Anywhere, just add a trivial C++ program somewhere

**Comment by horar** [comment]
create a file with name e.g. hello.cpp with following content:

    #include <iostream>
    #include <string>

    int main()
    {
	    std::cout << "Hello, world!\n";
    }

and commit them into this repository :-)

**Comment by vikaskyadav** [comment]
Please do guide how much I can contribute more.:)
