### ISSUE TITLE
Add extra cuda-related high-performance-primitives/components 

### ISSUE THREAD

**Issue by CheYulin** [fffaraz/awesome-cpp#258]
https://github.com/NVIDIA/nccl
- all-reduce, all-gather, reduce-scatter, reduce, broadcast

https://github.com/NVlabs/cub
- CUB provides state-of-the-art, reusable software components for every layer of the CUDA programming model

https://github.com/moderngpu/moderngpu
- moderngpu is a productivity library for general-purpose computing on GPUs. It is a header-only C++ library written for CUDA. The unique value of the library is in its accelerated primitives for solving irregularly parallel problems.

**Comment by fffaraz** [comment]
Please go ahead and open a pull request for these libs.

**Comment by CheYulin** [comment]
@fffaraz  I have open a [pull request ](https://github.com/fffaraz/awesome-cpp/pull/259), adding the above three libraries
