### ISSUE TITLE
Lack of documentation generation category.

### ISSUE THREAD

**Issue by Predelnik** [fffaraz/awesome-cpp#327]
This is such an important part for language users and seeing how many people are for various reasons are not entirely happy with doxygen it'd be cool to list some viable alternatives.

Approximate list of links to tools I've found, just for reference:
* https://github.com/doxygen/doxygen
* https://github.com/jessevdk/cldoc
* https://github.com/foonathan/standardese
* https://github.com/michaeljones/breathe
* https://github.com/copperspice/doxypress

I would personally would like to see more alternatives, partially that's why I'm creating this issue 😉  But seeing it merged to the list would be nice too.

awesome-python, awesome-c, awesome-ruby feature such tools in their lists.

**Comment by fffaraz** [comment]
It would be great if you make a pull request for this.
