### ISSUE TITLE
SQLite C++ Wrappers

### ISSUE THREAD

**Issue by Ninja-007** [fffaraz/awesome-cpp#345]
https://github.com/fnc12/sqlite_orm
https://github.com/rbock/sqlpp11-connector-sqlite3
https://github.com/aminroosta/sqlite_modern_cpp

**Comment by fffaraz** [comment]
aminroosta/sqlite_modern_cpp already exists.

**Comment by jgsogo** [comment]
I personally find this one very interesting: http://ed.am/dev/sqlite3cc It's not complete, but we can contribute and improve it.

**Comment by fnc12** [comment]
what about https://github.com/fnc12/sqlite_orm ?

**Comment by myd7349** [comment]
@Ninja-007 @fnc12 `sqlite_orm` is fixed by #411 :)
