### ISSUE TITLE
"C/C++" is not a language.

### ISSUE THREAD

**Issue by kmhofmann** [fffaraz/awesome-cpp#431]
There is no such mythical language as "C/C++", but there is (the ancient) C, and there is C++. As such, I think this collection should be called "A curated list of awesome C++ (or C) frameworks...".

See also this comment on reddit: https://www.reddit.com/r/cpp/comments/7qc87d/a_curated_list_of_awesome_cc_frameworks_libraries/dspnqc1/. It is not from me, but I wholeheartedly agree with it.

**Comment by Areustle** [comment]
"C/C++" is a very common idiom however. Is there a new movement to deprecate "C/C++"?

**Comment by fffaraz** [comment]
I agree too. But how does that fact change the usability and helpfulness of the actual content of this list?

**Comment by kmhofmann** [comment]
It _unfortunately_ is, and it is mostly used by people who have absolutely no idea that C++ is a completely separate language with completely different idioms and programming paradigms. There is no reason to conflate it with C, or to always mention the two languages together in the same breath.

**Comment by kmhofmann** [comment]
It doesn't change the usability or helpfulness of the actual list content a single bit. But proper separation of the languages might make reading this list a bit more palatable for people like me who are allergic to the usage of "C/C++" in writing, be it on GitHub or on resumes, or elsewhere. And trust me, it's not just me :-).

**Comment by msteinbeck** [comment]
To be honest, and for the sake of brevity, using 'C/C++' is completely fine.

**Comment by eXpl0it3r** [comment]
Nobody said C/C++ is a language, it's simply a separation character. 😉

**Comment by kmhofmann** [comment]
Technically speaking, maybe, but I have seen far too many lists like this: "Python, C/C++, Java, Haskell" that "C/C++" has become a real anti-pattern for many. Happy to send a pull request if there's a chance that it gets accepted.

**Comment by jpetso** [comment]
To be fair, C is not a completely different language from C++ as it's included in the latter in its entirety. Of course C++ has many different idioms and additional stuff, and there are certain habits useful for pure C that you might have never learned if you always had the full power and best practices of C++ at your disposal. That said, C++ developers are by necessity also familiar with C, will use C libraries natively with their original function signatures, and rely on the same underlying memory model.

As a C++ developer, I will take a good C library over a mediocre C++ library anytime, so conflating the two makes perfect sense for an "awesome" list. As a judge of skills, when I see someone mentioning "C/C++" then I assume they're a C++ developer with enough confidence to also handle the C subset of C++ competently. So really I think you guys are just splitting hairs and I don't see why one should read as much of a negative sense into it to call it an "anti-pattern".

**Comment by kmhofmann** [comment]
> as it's included in the latter in its entirety.

This is simply untrue. There are plenty of valid C programs that do not compile as C++, e.g. due to stricter type checking. Also, the C "subset" in C++ has diverged from C as in C11.

> As a C++ developer, I will take a good C library over a mediocre C++ library

Of course. I will also sometimes take a well-written Python or Java or Ruby library over a bad C++ one. Still not a reason to conflate C and C++. *They are completely different languages in practice and should be treated as such.*

> when I see someone mentioning "C/C++" then I assume they're a C++ developer with enough confidence to also handle the C subset of C++ competently

A truly knowledgeable C++ programmer will be able to do this in any case, without having to name-drop C, although (s)he will tend to avoid C idioms that have fallen out of favor in C++ (for good reason).
From my experience, the vast majority of people claiming to be good in the mythical "C/C++" language are okay at C, and quite terrible at or largely unfamiliar with (modern) C++, since they write C-style C++.

**Comment by eXpl0it3r** [comment]
> They are completely different languages in practice and should be treated as such.

Yes and no. The languages are different and the idioms as well, but in practice everyone is using C libraries and C APIs in their application, so it's perfectly fine to list them on this list as well.

C/C++ is not used wrongly here and nobody has been confused by its usage in this context so far.

**Comment by jpetso** [comment]
> This is simply untrue. There are plenty of valid C programs that do not compile as C++, e.g. due to stricter type checking. Also, the C "subset" in C++ has diverged from C as in C11.

True, and again, splitting hairs. I take no issue with the points that you bring up, and I have no qualms about changing the terms used in this repository. I merely don't agree that it would be necessarily wrong, or should be the cause of an allergic reaction, when people use the term to suggest that there is a significant overlap of C and C++, causing them to know and use both in the same context.

Extrapolating from the use of this term to people's attitudes of idioms and knowledge of modern C++ is your interpretation. Everyone is entitled to an opinion.

**Comment by Aarowaim** [comment]
C and C++ have been co-evolving due to compiler support. If idioms were the only measure of divergence in languages, there would need to be many different "C++" languages due to the sheer scale of what is included in its feature set. Depending on the nature of a project, a programmer can spend many years without touching one of RAII, templates, or manual allocation.

It should be noted that although the heading is "A curated list of awesome **C/C++** frameworks", the descriptions specify which of C or C++ a particular library belongs to. However many of the libraries are cross-compatible, implying that C/C++ is a useful generalization.

**Comment by Areustle** [comment]
Of possible note here is the fact that there is another awesome list for the C language: https://github.com/aleksandar-todorovic/awesome-c
And somewhat confusingly in the Meta awesome list under programming languages this
project is listed as "C/C++" following that prior one of just "C". It kind of demotes C++.
https://github.com/sindresorhus/awesome
screencap:

<img width="139" alt="screen shot 2018-01-30 at 7 44 11 pm" src="https://user-images.githubusercontent.com/2585847/35599283-017ea5b8-05f6-11e8-8294-4bda8836c8a5.png">

**Comment by kmhofmann** [comment]
Just submitted a pull request ^^  that removes the unholy "C/C++" combination from most parts of the document... except for project self-descriptions, where "C/C++" is unfortunately mentioned.

@Aarowaim: There is only one C++ language (with various evolving standards), and one C language (ditto), and they're both pretty distinct. A C++ programmer who is not familiar with RAII or templates is either a very inexperienced C++ programmer, has the wrong teaching materials, or remains stuck in the mid-'90s; this has relatively little to do with the nature of projects.

@Areustle This is one of the unfortunate side effects of conflating C and C++.

**Comment by Aarowaim** [comment]
@kmhofmann You glazed over a lot of my comment. You may split hairs with us, but you don't allow us to split hairs with you. My stance is reflected in a previous comment.

> The languages are different and the idioms as well, but in practice everyone is using C libraries and C APIs in their application, so it's perfectly fine to list them on this list as well.

> C/C++ is not used wrongly here and nobody has been confused by its usage in this context so far.

You are Quixote here, a figure fighting in a glorious crusade against "unholiness" that causes no damage to the vast majority of programmers. Pedantry of this sort distracts from meaningful progress.

**Comment by kmhofmann** [comment]
If that is your opinion, then so be it -- I have no intention of changing any of that, and I'll take the compliment. :)
However, I do not think this is pedantry, but merely correctness, and proper attribution of a language that (too) often gets thrown into the same pot as one of its spiritual predecessors. The two languages could not be more different today, by all practical means and purposes.

**Comment by douglasm42** [comment]
I just want to add a few things to the discussion.

In natural languages the slash generally means 'or', so 'C/C++' means 'C or C++', like he/she. I don't understand why this is wrong. It indicates that either language works or is accepted/correct in the context, like most/all C libraries/frameworks in this list.

On the other hand, there is a lot of libraries that support other languages on this list, like Java, Python, JavaScript, Ruby, C#, PHP and Perl.

So, if the only requirement to something enter on this list is that it have to support C++, then the correct name is Awesome C++ and the '(or C)' should be removed from 'A curated list of awesome C++ (or C) frameworks...'

But if the requirement is that it have to support C++ or C, than 'Awesome C/C++' or 'Awesome C or C++' is a better name.

**Comment by kmhofmann** [comment]
Yeah, the title could be either 'Awesome C++' or 'Awesome C++ (or C)', but I think the former has more focus on the fact that most libraries mentioned are C++ libraries. Many C libraries happen to interoperate with C++ libraries, but often it's not the other way around (unless there's an explicit C API). And the repo name in the URL is 'awesome-cpp', so I just went with the shorter version in the PR, although the longer one is more correct (but less succinct sounding).

Semantically you are of course correct, 'C/C++' could mean 'C or C++'. In practice, however, if I had a dollar (or Euro) for each time I see it mentioned as in 'Java, Python, C/C++, Rust, ...', I could have bought something really nice from that. Same for the number of times someone writes 'C/C++' while referring to what's actually plain C code. I take this as a strong hint that many people don't make a proper distinction between the languages, which is a shame.

There are a lot of people in the C++ community who advocate *not* teaching C when wanting to learn C++ (see e.g. https://youtu.be/YnWhqhNdYyk), and getting rid of the 'C/C++' wording can be a small contribution toward changing the mindset.
