### ISSUE TITLE
EnTT - Gaming meets modern C++

### ISSUE THREAD

**Issue by skypjack** [fffaraz/awesome-cpp#475]
Hi,

I would like to add [`EnTT`](https://github.com/skypjack/entt) to this awesome list.  
Description - _Gaming meets modern C++ - a fast and reliable entity-component system and much more_.
License MIT.

It's a sort of framework with a lot of stuff mainly oriented to game development.  
I think it's good match being it 100% modern C++. However I'm not sure about what's the best section to propose it, probably frameworks or game engine.  
Any suggestion or rules of which I should be aware before to create a PR?

Thank you.

**Comment by fffaraz** [comment]
I guess it should be in the Game Engine section. Just send a pull request and I'll merge it.
