### ISSUE TITLE
JSON: jq

### ISSUE THREAD

**Issue by myd7349** [fffaraz/awesome-cpp#478]
Is [jq](https://github.com/stedolan/jq) awesome enough to be added to the `JSON` section?
`jq` announces itself a command line JSON processor. [wikipedia](https://en.wikipedia.org/wiki/Jq_(programming_language)) says that `jq` is a programming language(just like `sed`, `awk`), though.

**Comment by fffaraz** [comment]
Can it be also used as a library?

**Comment by myd7349** [comment]
Nope, I didn't see this usage. 
I may close this issue.
