### ISSUE TITLE
pocketsphinx_continuous

### ISSUE THREAD

**Issue by sunliam** [fffaraz/awesome-cpp#545]
Hi Folks，

I'm using pocketsphinx on an embedded system for offline speech recognition. It works good for me. However, I met an issue when applied to keyword recognition. The case is described as follows:

There are ten keywords included in the gram file. When a speaker says a keyword through usb mic, the executable program pocketsphinx_continuous displays the corresponding text in console output. However, when the input keyword does not exist in the gram file,  a text is still output even these are two totally different words. I understand the engine will select the best one whose score is the highest. But is there any solution to such case? i.e, the text should not be displayed if the input keyword through microphone does not exist in the gram file. 

command line for executing pocketsphinx_continuous:
./pocketsphinx_continuous -hmm../share/pocketsphinx/model/en-us/en-us -dict../share/pocketsphinx/model/en-us/cmudict-en-us.dict -inmic yes -adcdev "hw:2,0" -samprate 16000 -jsgf ./keywords.gram

where keywords.gram is a customized grammar file including keywords to be recognized.

**Comment by Kojoley** [comment]
You are in the wrong place. The pocketsphinx issue tracker is located there https://github.com/cmusphinx/pocketsphinx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by sunliam** [comment]
Got it, thanks
