### ISSUE TITLE
cxxomfort (update)

### ISSUE THREAD

**Issue by lmachucab** [fffaraz/awesome-cpp#656]
Update cxxomfort entry as follows:

* [Cxxomfort](http://ryan.gulix.cl/fossil.cgi/cxxomfort/) - A small, header-only library that backports various facilities from more recent C++ Standards to C++03 and later. [MIT]

**Comment by myd7349** [comment]
Thanks for the suggestion. Feel free to create a PR. :)

**Comment by lmachucab** [comment]
....Duh I can't believe I missed the obvious thing to do, will get to that!
