### ISSUE TITLE
How about renaming "Remote Procedure Call" to "Inter-process Communication"?

### ISSUE THREAD

**Issue by myd7349** [fffaraz/awesome-cpp#68]
The wikipedia says:

[Remote procedure call](http://en.wikipedia.org/wiki/Remote_procedure_call)
>In computer science, a remote procedure call (RPC) is an [inter-process communication](http://en.wikipedia.org/wiki/Inter-process_communication) that allows a computer program to cause a subroutine or procedure to execute in another address space (commonly on another computer on a shared network) without the programmer explicitly coding the details for this remote interaction.

[Message queue](http://en.wikipedia.org/wiki/Message_queue)
>In computer science, message queues and mailboxes are software-engineering components used for inter-process communication (IPC), or for inter-thread communication within the same process. They use a queue for messaging – the passing of control or of content. Group communication systems provide similar kinds of functionality.

So, how about adding a new category "Inter-process Communication" and treating "Remote Procedure Call" as a sub category of it?

Or, should I add a new category: Message Queue/Messaging Library, and put ZeroMQ, nanomsg, ... under this category? Since there are so many messaging libraries and most of them not only support IPC but also support other kind of communications(in-thread communication, for instance).

Sometimes, it may be a little difficult for me to decide which category should a library belonging to.

**Comment by fffaraz** [comment]
Let's have all those message queue and RPC libraries in the same Inter-process Communication section for now.
https://github.com/fffaraz/awesome-cpp#inter-process-communication

**Comment by myd7349** [comment]
:)
