### ISSUE TITLE
miniz

### ISSUE THREAD

**Issue by myd7349** [fffaraz/awesome-cpp#687]
The repo link should be updated to: https://github.com/richgel999/miniz

Is the license still `Unlicense` or changed to `MIT`?

**Comment by eXpl0it3r** [comment]
Tried to reach out to the maintainer on Twitter. Let's see.

According to the commit message, it was set to MIT because it apparently evolved out of some Valve project that was MIT. But then I wonder why it still says as first "Feature" on the Google Code site that it's Unlicense.

**Comment by eXpl0it3r** [comment]
The original author has handed over the project. I've opened [an issue](https://github.com/richgel999/miniz/issues/120) as I wasn't able to find a way to contact the new maintainer otherwise.
