### ISSUE TITLE
Intel GameTaskScheduler

### ISSUE THREAD

**Issue by Lectem** [fffaraz/awesome-cpp#730]
> GTS is a light-weight, C++, experimental task scheduling framework designed with a "Bring Your Own Engine/Framework" style. It consists of a work-stealing micro-scheduler and a persistent DAG macro-scheduler. It also incorporates parallel containers, threading constructs, and debugging utilities.

https://github.com/GameTechDev/GTS-GamesTaskScheduler

This task scheduler kind of is the state of the art for games, but I think it also applies to any application that needs parallelism/concurrency.

**Comment by myd7349** [comment]
Hey! @Lectem Thanks for the advice. A PR will be appreciated.
