### ISSUE TITLE
PEGTL out of date

### ISSUE THREAD

**Issue by myd7349** [fffaraz/awesome-cpp#767]
The repository link is out of date:
>https://github.com/taocpp/PEGTL

**Comment by data-man** [comment]
Please add [cpp-peglib](https://github.com/yhirose/cpp-peglib).

**Comment by myd7349** [comment]
> 
> 
> Please add [cpp-peglib](https://github.com/yhirose/cpp-peglib).

Hi! @data-man Thanks for your advice. I have created a new issue for tackling this. A PR is welcome.
