### ISSUE TITLE
Open source Facebook' C++ projects

### ISSUE THREAD

**Issue by stunpix** [fffaraz/awesome-cpp#786]
[Buck](https://github.com/facebook/buck) - A fast build system that encourages the creation of small, reusable modules over a variety of platforms and languages including C++ developed and used at Facebook. Written in Java.

[Folly](https://github.com/facebook/folly)  - (acronymed loosely after Facebook Open Source Library) is a library of C++14 components designed with practicality and efficiency in mind

[Infer](https://github.com/facebook/infer) - A static analyzer for Java, C, C++, and Objective-C developed and used at Facebook.

[Proxygen](https://github.com/facebook/proxygen) - A collection of C++ HTTP libraries including an easy to use HTTP server developed and used at Facebook.

**Comment by myd7349** [comment]
Hi! @stunpix Thanks for your suggestion. We already have `Folly` on the list: https://github.com/fffaraz/awesome-cpp/blame/master/README.md#L90.
Would you like to create some PRs for the other 3 libraries/tools you mentioned.

**Comment by stunpix** [comment]
Ah, yep, I see that Infer and Proxygen I didn't noted as well, so I've created a PR that contains only Buck.
