### ISSUE TITLE
Can't navigate to multi-word headers using the navigation

### ISSUE THREAD

**Issue by drasive** [fffaraz/awesome-cpp#82]
You can't navigate to a multi-word header (e.g. "Artificial Intelligence" or "Machine Learning") using the navigation section at the top on [fffaraz.github.io/awesome-cpp/](https://fffaraz.github.io/awesome-cpp/).
This is because the words in the href attributes of the navigation are split with "-" (e.g. a 'href="#machine*-*learning"') but the section ids don't have anything between the words in their id attributes (e.g. '<h2 id="machinelearning"').

**Comment by nickdesaulniers** [comment]
:+1:

**Comment by elador** [comment]
I find it interesting to note that when displaying the README.md on Github, the anchors work, while they don't work on http://fffaraz.github.io/awesome-cpp/.

The HTML code differs:

`<h2 id="standardlibraries">Standard Libraries</h2>` on http://fffaraz.github.io/awesome-cpp/, vs `<h2><a id="user-content-standard-libraries" class="anchor" href="#standard-libraries" aria-hidden="true"><span class="octicon octicon-link"></span></a> [...]` on here.

There seem to be two different Markdown renderers at work?

**Comment by fffaraz** [comment]
Yes, I have used (probably an old version of) showdown.js.
https://github.com/showdownjs/showdown

Please take a look at the gh-pages branch of this repo.
