### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [fffaraz/awesome-cpp#92]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by fffaraz** [comment]
When you say 'we', who exactly are you referring to?
Is there any reason why I might want to transfer my repo to your account?! Even if you add me as an admin, along with several others having write access to all the other repos. This is just stupid if you ask my opinion.
You can fork this repo and maintain it for your "organization" and also keep "higher visibility" and "more stars" for your own fork cause that's not why I created this list.
Thank you!

**Comment by jeffreyjackson** [comment]
while i understand thats not the reason you created this list, we are asking you to help us build an organization where "we" (you and I and others) have a place for everything awesome.  You don't lose anything by doing this.  You will remain as an admin.  We're just looking to create a team where we all move forward in a direction that has a similar format and structure.  Thank you for your consideration.

**Comment by fffaraz** [comment]
I'm sorry. It's 2015, the Soviet Union fell apart 25 years ago.
Have fun "moving forward in a direction that has a similar format and structure".

**Comment by Trevoke** [comment]
As a random bystander, I think there is some value in an organization where this is maintained by a group of collaborators.

I do also think that "we" is a very scary and vague word, especially when "we" is the entity that wants to do good.
